#!/usr/bin/env python3
# create the list called vendors
vendors = ["*"]
# loop across the list vendors
for x in vendors:
    print(\x)  # each time through the loop print value of x
print("\nOur loop has ended.")  # when the loop ends print this

